// Generated by CoffeeScript 1.6.3
var App, GameRenderer,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

GameRenderer = (function() {
  GameRenderer.prototype.renderer = null;

  GameRenderer.prototype.stage = null;

  function GameRenderer(view) {
    this.view = view;
    this.render = __bind(this.render, this);
    this.renderer = PIXI.autoDetectRenderer(window.innerWidth, window.innerHeight);
    this.stage = new PIXI.Stage(0x000000);
    this.view.appendChild(this.renderer.view);
  }

  GameRenderer.prototype.render = function() {
    return this.renderer.render(this.stage);
  };

  return GameRenderer;

})();

App = (function() {
  App.prototype.renderer = null;

  function App() {
    this.update = __bind(this.update, this);
    this.renderer = new GameRenderer(document.getElementById('game-holder'));
    requestAnimationFrame(this.update);
  }

  App.prototype.update = function() {
    this.renderer.render();
    return null;
  };

  return App;

})();
