class Levels

	@EmptyLevel:{
		pickups:{},
		startPos:{x:0, y:0}
	}

	@LevelOne:{
		pickups:{
			"3_6" : "true",
			"5_4" : "true",
			"7_2" : "true",
		},
		startPos:{
			x:3,
			y:2
		},
		"1_5" : "falling",
		"1_6" : "falling",
		"1_7" : "falling",
		"2_7" : "falling",
		"3_2" : "corner",
		"3_4" : "metal",
		"3_5" : "jump",
		"3_6" : "falling",
		"3_7" : "metal",
		"4_2" : "metal",
		"4_4" : "metal",
		"4_5" : "metal",
		"4_7" : "falling",
		"5_2" : "metal",
		"5_4" : "metal",
		"5_7" : "falling",
		"6_2" : "metal",
		"6_7" : "falling",
		"7_2" : "metal",
		"7_4" : "jump",
		"7_7" : "falling",
		"8_2" : "metal",
		"8_3" : "metal",
		"8_4" : "metal",
		"8_7" : "exit_open"
	}

	@LevelTwo:{
		pickups:{
			"4_3" : "true",
			"4_7" : "true",
		},
		startPos:{
			x:1,
			y:3
		},
		"1_3" : "corner",
		"1_7" : "exit_closed",
		"2_3" : "metal",
		"2_7" : "metal",
		"3_3" : "metal",
		"3_4" : "metal",
		"3_7" : "metal",
		"4_3" : "metal",
		"4_4" : "jump",
		"4_7" : "metal",
		"5_3" : "metal",
		"5_7" : "metal",
		"6_3" : "metal",
		"6_4" : "jump",
		"6_6" : "metal",
		"6_7" : "metal",
		"7_6" : "falling",
		"8_4" : "falling",
		"8_5" : "falling",
		"8_6" : "falling"
	}

	@LevelThree:{
		pickups:{
			"4_4" : "true",
			"7_4" : "true",
			"7_7" : "true",
		},
		startPos:{
			x:1,
			y:3
		},
		"1_3" : "corner",
		"1_7" : "exit_closed",
		"2_3" : "metal",
		"2_7" : "falling",
		"3_3" : "jump",
		"3_7" : "falling",
		"4_4" : "falling",
		"4_5" : "falling",
		"4_6" : "falling",
		"4_7" : "falling",
		"5_3" : "jump",
		"6_2" : "metal",
		"6_3" : "metal",
		"6_4" : "jump",
		"6_6" : "metal",
		"6_7" : "metal",
		"7_3" : "falling",
		"7_4" : "metal",
		"7_6" : "jump",
		"7_7" : "metal"
	}

	@LevelFour:{
		pickups:{
			"1_3" : "true",
			"4_2" : "true",
			"8_7" : "true",
		},
		startPos:{
			x:4,
			y:8
		},
		"1_3" : "metal",
		"1_4" : "metal",
		"1_5" : "metal",
		"2_3" : "metal",
		"2_5" : "jump",
		"3_3" : "metal",
		"3_4" : "metal",
		"3_6" : "jump",
		"3_7" : "metal",
		"4_1" : "exit_open",
		"4_2" : "metal",
		"4_4" : "jump",
		"4_5" : "jump",
		"4_6" : "jump",
		"4_7" : "metal",
		"4_8" : "corner",
		"5_4" : "metal",
		"5_6" : "jump",
		"5_7" : "metal",
		"6_5" : "metal",
		"6_6" : "falling",
		"6_7" : "falling",
		"7_5" : "metal",
		"7_6" : "falling",
		"7_7" : "jump",
		"8_6" : "falling",
		"8_7" : "metal"
	}

	@LevelFive:{
		pickups:{
			"2_4" : "true",
			"4_4" : "true",
			"4_7" : "true",
			"7_4" : "true",
		},
		startPos:{
			x:4,
			y:0
		},
		"2_3" : "falling",
		"2_4" : "metal",
		"2_5" : "falling",
		"3_3" : "metal",
		"3_5" : "metal",
		"4_0" : "corner",
		"4_1" : "jump",
		"4_3" : "falling",
		"4_4" : "metal",
		"4_5" : "jump",
		"4_7" : "jump",
		"4_9" : "exit_open",
		"5_3" : "metal",
		"5_5" : "metal",
		"6_3" : "falling",
		"6_4" : "jump",
		"6_5" : "falling",
		"7_3" : "metal",
		"7_4" : "metal",
		"7_5" : "metal",
	}

	@LevelSix:{
		pickups:{
			"3_3" : "true",
			"3_6" : "true",
			"6_3" : "true",
			"6_6" : "true",
		},
		startPos:{
			x:4,
			y:1
		},
		"3_3" : "falling",
		"3_4" : "jump",
		"3_5" : "metal",
		"3_6" : "falling",
		"4_1" : "corner",
		"4_2" : "jump",
		"4_3" : "falling",
		"4_4" : "metal",
		"4_5" : "falling",
		"4_6" : "jump",
		"5_3" : "jump",
		"5_4" : "falling",
		"5_5" : "falling",
		"5_6" : "metal",
		"6_3" : "falling",
		"6_4" : "metal",
		"6_5" : "jump",
		"6_6" : "falling",
		"7_3" : "metal",
		"7_4" : "jump",
		"7_6" : "exit_closed"
	}

	@LevelSeven:{
		pickups:{
			"0_8" : "true",
			"1_2" : "true",
			"1_5" : "true",
			"4_4" : "true",
			"5_2" : "true",
			"5_8" : "true",
			"8_2" : "true",
			"8_8" : "true"
		},
		startPos:{
			x:1,
			y:8
		},
		"0_5" : "metal",
		"0_8" : "falling",
		"1_1" : "metal",
		"1_2" : "falling",
		"1_4" : "jump",
		"1_5" : "metal",
		"1_7" : "jump",
		"1_8" : "corner",
		"2_1" : "metal",
		"2_5" : "jump",
		"2_8" : "jump",
		"3_1" : "jump",
		"4_2" : "metal",
		"4_4" : "falling",
		"4_5" : "falling",
		"4_8" : "jump",
		"5_1" : "metal",
		"5_2" : "falling",
		"5_4" : "falling",
		"5_5" : "jump",
		"5_7" : "falling",
		"5_8" : "falling",
		"6_2" : "jump",
		"6_7" : "jump",
		"7_8" : "jump",
		"7_9" : "metal",
		"8_2" : "falling",
		"8_3" : "metal",
		"8_4" : "metal",
		"8_5" : "jump",
		"8_7" : "exit_open",
		"8_8" : "falling"
	}

	@LevelEight:{
		pickups:{
			"1_1" : "true",
			"3_3" : "true",
			"3_6" : "true",
			"6_3" : "true",
			"6_6" : "true",
			"8_8" : "true",
		},
		startPos:{
			x:6,
			y:1
		},
		"1_1" : "metal",
		"1_2" : "metal",
		"1_3" : "metal",
		"1_4" : "metal",
		"1_5" : "metal",
		"1_6" : "metal",
		"1_7" : "falling",
		"1_8" : "exit_open",
		"2_1" : "falling",
		"2_6" : "falling",
		"2_8" : "falling",
		"3_1" : "metal",
		"3_2" : "falling",
		"3_3" : "metal",
		"3_4" : "falling",
		"3_5" : "metal",
		"3_6" : "metal",
		"3_8" : "metal",
		"4_1" : "metal",
		"4_3" : "metal",
		"4_6" : "falling",
		"4_8" : "metal",
		"5_1" : "metal",
		"5_3" : "falling",
		"5_6" : "metal",
		"5_8" : "metal",
		"6_1" : "corner",
		"6_3" : "metal",
		"6_4" : "metal",
		"6_5" : "falling",
		"6_6" : "metal",
		"6_7" : "falling",
		"6_8" : "metal",
		"7_1" : "metal",
		"7_3" : "falling",
		"7_8" : "falling",
		"8_1" : "falling",
		"8_2" : "metal",
		"8_3" : "metal",
		"8_4" : "metal",
		"8_5" : "metal",
		"8_6" : "metal",
		"8_7" : "metal",
		"8_8" : "metal"
	}

	@LevelNine:{
		pickups:{
			"0_1" : "true",
			"0_8" : "true",
			"3_3" : "true",
			"6_5" : "true",
			"9_7" : "true",
		},
		startPos:{
			x:2,
			y:1
		},
		"0_0" : "metal",
		"0_1" : "metal",
		"0_2" : "metal",
		"0_7" : "metal",
		"0_8" : "falling",
		"0_9" : "metal",
		"1_0" : "falling",
		"1_2" : "falling",
		"1_3" : "metal",
		"1_4" : "metal",
		"1_5" : "metal",
		"1_6" : "metal",
		"1_7" : "metal",
		"1_9" : "metal",
		"2_0" : "metal",
		"2_1" : "corner",
		"2_2" : "metal",
		"2_7" : "metal",
		"2_8" : "falling",
		"2_9" : "metal",
		"3_3" : "metal",
		"3_4" : "metal",
		"3_5" : "metal",
		"3_6" : "metal",
		"3_8" : "metal",
		"4_3" : "metal",
		"4_5" : "metal",
		"4_6" : "falling",
		"4_7" : "falling",
		"4_8" : "metal",
		"5_3" : "falling",
		"5_4" : "metal",
		"5_6" : "metal",
		"5_8" : "falling",
		"6_0" : "metal",
		"6_1" : "falling",
		"6_2" : "metal",
		"6_3" : "metal",
		"6_4" : "metal",
		"6_5" : "metal",
		"6_6" : "metal",
		"6_8" : "falling",
		"7_0" : "jump",
		"7_6" : "falling",
		"7_7" : "falling",
		"7_8" : "metal",
		"7_9" : "metal",
		"8_9" : "metal",
		"9_0" : "exit_open",
		"9_1" : "metal",
		"9_3" : "jump",
		"9_5" : "jump",
		"9_7" : "jump",
		"9_8" : "falling",
		"9_9" : "metal"
	}

	@LevelTen:{
		pickups:{
			"2_7" : "true",
			"3_3" : "true",
			"6_6" : "true",
			"7_2" : "true",
		},
		startPos:{
			x:1,
			y:1
		},
		"1_1" : "corner",
		"1_2" : "falling",
		"1_3" : "metal",
		"1_4" : "metal",
		"1_5" : "metal",
		"1_6" : "metal",
		"2_1" : "falling",
		"2_2" : "falling",
		"2_6" : "falling",
		"2_7" : "falling",
		"3_1" : "metal",
		"3_3" : "metal",
		"3_4" : "metal",
		"3_5" : "metal",
		"3_6" : "falling",
		"3_7" : "falling",
		"3_8" : "metal",
		"4_1" : "metal",
		"4_3" : "metal",
		"4_6" : "metal",
		"4_8" : "metal",
		"5_1" : "metal",
		"5_3" : "falling",
		"5_6" : "metal",
		"5_8" : "metal",
		"6_1" : "metal",
		"6_2" : "metal",
		"6_3" : "metal",
		"6_4" : "falling",
		"6_5" : "metal",
		"6_6" : "metal",
		"6_7" : "falling",
		"6_8" : "metal",
		"7_2" : "falling",
		"7_3" : "metal",
		"7_7" : "exit_open",
		"7_8" : "falling",
		"8_3" : "metal",
		"8_4" : "metal",
		"8_5" : "metal",
		"8_6" : "metal",
		"8_7" : "falling"
	}

	@LevelEleven:{
		pickups:{
			"1_1" : "true",
			"2_6" : "true",
			"4_2" : "true",
			"7_5" : "true",
			"8_2" : "true",
			"8_8" : "true",
		},
		startPos:{
			x:2,
			y:7
		},
		"1_1" : "falling",
		"1_2" : "metal",
		"2_0" : "metal",
		"2_2" : "jump",
		"2_3" : "metal",
		"2_5" : "jump",
		"2_6" : "metal",
		"2_7" : "corner",
		"3_0" : "metal",
		"3_1" : "jump",
		"3_7" : "metal",
		"4_1" : "metal",
		"4_2" : "metal",
		"4_3" : "jump",
		"4_4" : "metal",
		"4_7" : "jump",
		"5_1" : "jump",
		"5_3" : "metal",
		"5_4" : "falling",
		"5_7" : "jump",
		"6_7" : "jump",
		"7_1" : "jump",
		"7_2" : "metal",
		"7_4" : "jump",
		"7_5" : "metal",
		"7_7" : "jump",
		"7_8" : "metal",
		"8_1" : "metal",
		"8_2" : "metal",
		"8_4" : "metal",
		"8_5" : "metal",
		"8_7" : "metal",
		"8_8" : "metal",
		"9_1" : "exit_open"
	}

	@LevelTwelve:{
		pickups:{
			"0_0" : "true",
			"0_9" : "true",
			"2_2" : "true",
			"6_2" : "true",
			"9_0" : "true",
			"9_9" : "true",
		},
		startPos:{
			x:4,
			y:0
		},
		"0_0" : "metal",
		"0_1" : "falling",
		"0_2" : "falling",
		"0_3" : "falling",
		"0_4" : "falling",
		"0_5" : "falling",
		"0_6" : "falling",
		"0_7" : "falling",
		"0_8" : "falling",
		"0_9" : "metal",
		"1_0" : "metal",
		"1_9" : "metal",
		"2_0" : "metal",
		"2_2" : "metal",
		"2_3" : "metal",
		"2_5" : "jump",
		"2_6" : "metal",
		"2_8" : "jump",
		"2_9" : "falling",
		"3_0" : "metal",
		"3_2" : "jump",
		"3_3" : "metal",
		"3_6" : "metal",
		"3_7" : "metal",
		"3_9" : "metal",
		"4_0" : "corner",
		"4_7" : "falling",
		"4_9" : "metal",
		"5_0" : "exit_open",
		"5_7" : "falling",
		"5_9" : "metal",
		"6_0" : "metal",
		"6_2" : "metal",
		"6_3" : "metal",
		"6_6" : "metal",
		"6_7" : "metal",
		"6_9" : "metal",
		"7_0" : "metal",
		"7_2" : "jump",
		"7_3" : "metal",
		"7_5" : "jump",
		"7_6" : "metal",
		"7_8" : "jump",
		"7_9" : "falling",
		"8_0" : "metal",
		"8_9" : "metal",
		"9_0" : "metal",
		"9_1" : "falling",
		"9_2" : "falling",
		"9_3" : "falling",
		"9_4" : "falling",
		"9_5" : "falling",
		"9_6" : "falling",
		"9_7" : "falling",
		"9_8" : "falling",
		"9_9" : "metal"
	}

	@LevelThirteen:{
		pickups:{
			"3_3" : "true",
			"3_6" : "true",
			"6_3" : "true",
			"6_6" : "true",
		},
		startPos:{
			x:0,
			y:4
		},
		"0_3" : "metal",
		"0_4" : "corner",
		"0_5" : "metal",
		"0_6" : "metal",
		"1_3" : "falling",
		"1_6" : "falling",
		"2_3" : "falling",
		"2_6" : "falling",
		"3_3" : "metal",
		"3_4" : "falling",
		"3_5" : "falling",
		"3_6" : "metal",
		"4_3" : "falling",
		"4_6" : "falling",
		"5_3" : "falling",
		"5_6" : "falling",
		"6_3" : "metal",
		"6_4" : "falling",
		"6_5" : "falling",
		"6_6" : "metal",
		"7_3" : "jump",
		"7_6" : "jump",
		"9_3" : "metal",
		"9_4" : "falling",
		"9_5" : "exit_open",
		"9_6" : "metal"
	}

	@LevelFourteen:{
		pickups:{
			"0_3" : "true",
			"0_6" : "true",
			"1_1" : "true",
			"3_0" : "true",
			"7_8" : "true",
			"8_0" : "true",
			"8_7" : "true",
		},
		startPos:{
			x:3,
			y:3
		},
		"0_3" : "metal",
		"0_4" : "metal",
		"0_6" : "falling",
		"0_7" : "metal",
		"0_8" : "metal",
		"1_1" : "metal",
		"1_2" : "metal",
		"1_3" : "metal",
		"1_4" : "jump",
		"1_6" : "jump",
		"1_7" : "metal",
		"1_8" : "metal",
		"2_1" : "metal",
		"2_8" : "falling",
		"3_0" : "metal",
		"3_1" : "metal",
		"3_3" : "corner",
		"3_4" : "jump",
		"3_6" : "jump",
		"3_8" : "falling",
		"4_0" : "metal",
		"4_1" : "jump",
		"4_3" : "jump",
		"4_5" : "metal",
		"4_7" : "metal",
		"4_8" : "jump",
		"5_4" : "metal",
		"5_5" : "falling",
		"5_6" : "metal",
		"6_0" : "metal",
		"6_1" : "jump",
		"6_3" : "jump",
		"6_5" : "metal",
		"6_6" : "exit_closed",
		"6_8" : "jump",
		"7_0" : "metal",
		"7_1" : "metal",
		"7_4" : "metal",
		"7_8" : "falling",
		"7_9" : "falling",
		"8_0" : "metal",
		"8_1" : "metal",
		"8_2" : "metal",
		"8_3" : "falling",
		"8_4" : "jump",
		"8_6" : "jump",
		"8_7" : "falling",
		"8_8" : "metal",
		"8_9" : "falling",
		"9_7" : "falling",
		"9_8" : "falling",
		"9_9" : "falling"
	}

	@LevelFifteen:{
		pickups:{
			"0_0" : "true",
			"0_9" : "true",
			"2_4" : "true",
			"9_0" : "true",
			"9_9" : "true",
		},
		startPos:{
			x:3,
			y:4
		},
		"0_0" : "metal",
		"0_1" : "metal",
		"0_4" : "falling",
		"0_5" : "metal",
		"0_6" : "jump",
		"0_8" : "metal",
		"0_9" : "metal",
		"1_0" : "metal",
		"1_1" : "metal",
		"1_2" : "metal",
		"1_7" : "metal",
		"1_8" : "metal",
		"1_9" : "metal",
		"2_1" : "metal",
		"2_2" : "jump",
		"2_4" : "falling",
		"2_5" : "jump",
		"2_7" : "jump",
		"2_8" : "metal",
		"3_0" : "jump",
		"3_4" : "corner",
		"3_5" : "metal",
		"3_6" : "falling",
		"4_0" : "metal",
		"4_2" : "jump",
		"4_3" : "metal",
		"4_6" : "metal",
		"4_7" : "metal",
		"4_9" : "falling",
		"5_0" : "falling",
		"5_2" : "metal",
		"5_3" : "metal",
		"5_6" : "metal",
		"5_7" : "jump",
		"5_9" : "metal",
		"6_3" : "falling",
		"6_4" : "metal",
		"6_5" : "exit_open",
		"6_9" : "jump",
		"7_1" : "metal",
		"7_2" : "jump",
		"7_4" : "jump",
		"7_5" : "metal",
		"7_7" : "jump",
		"7_8" : "metal",
		"8_0" : "metal",
		"8_1" : "metal",
		"8_2" : "metal",
		"8_7" : "metal",
		"8_8" : "metal",
		"8_9" : "metal",
		"9_0" : "metal",
		"9_1" : "metal",
		"9_3" : "jump",
		"9_4" : "metal",
		"9_5" : "falling",
		"9_8" : "metal",
		"9_9" : "metal"
	}

	@LevelSixteen:{
		pickups:{
			"2_2" : "true",
			"2_7" : "true",
			"7_2" : "true",
			"7_7" : "true",
		},
		startPos:{
			x:4,
			y:9
		},
		"1_4" : "metal",
		"1_5" : "metal",
		"2_2" : "metal",
		"2_3" : "metal",
		"2_4" : "falling",
		"2_5" : "falling",
		"2_6" : "jump",
		"2_7" : "metal",
		"3_2" : "jump",
		"3_4" : "metal",
		"3_5" : "jump",
		"3_7" : "metal",
		"4_1" : "metal",
		"4_2" : "falling",
		"4_3" : "metal",
		"4_4" : "metal",
		"4_5" : "metal",
		"4_6" : "metal",
		"4_7" : "falling",
		"4_8" : "jump",
		"4_9" : "corner",
		"5_1" : "exit_open",
		"5_2" : "falling",
		"5_3" : "jump",
		"5_4" : "metal",
		"5_5" : "metal",
		"5_6" : "jump",
		"5_7" : "falling",
		"5_8" : "metal",
		"6_2" : "metal",
		"6_4" : "metal",
		"6_5" : "jump",
		"6_7" : "metal",
		"7_2" : "metal",
		"7_3" : "jump",
		"7_4" : "falling",
		"7_5" : "falling",
		"7_6" : "metal",
		"7_7" : "metal",
		"8_4" : "metal",
		"8_5" : "metal"
	}

	@LevelSeventeen:{
		pickups:{
			"1_1" : "true",
			"1_8" : "true",
			"8_1" : "true",
			"8_8" : "true",
		},
		startPos:{
			x:5,
			y:5
		},
		"1_1" : "metal",
		"1_2" : "metal",
		"1_3" : "metal",
		"1_5" : "metal",
		"1_6" : "jump",
		"1_7" : "metal",
		"1_8" : "metal",
		"2_1" : "metal",
		"2_3" : "falling",
		"2_8" : "metal",
		"3_1" : "jump",
		"3_3" : "metal",
		"3_5" : "jump",
		"3_6" : "metal",
		"3_7" : "falling",
		"3_8" : "metal",
		"4_3" : "metal",
		"4_4" : "exit_open",
		"4_5" : "metal",
		"5_1" : "falling",
		"5_4" : "metal",
		"5_5" : "corner",
		"5_6" : "metal",
		"6_1" : "metal",
		"6_2" : "falling",
		"6_3" : "metal",
		"6_4" : "metal",
		"6_6" : "metal",
		"6_8" : "jump",
		"7_1" : "metal",
		"7_6" : "falling",
		"7_8" : "metal",
		"8_1" : "metal",
		"8_2" : "metal",
		"8_3" : "jump",
		"8_5" : "metal",
		"8_6" : "metal",
		"8_7" : "metal",
		"8_8" : "metal"
	}

	@LevelEighteen:{
		pickups:{
			"1_1" : "true",
			"1_8" : "true",
			"8_1" : "true",
			"8_8" : "true",
		},
		startPos:{
			x:5,
			y:4
		},
		"1_1" : "metal",
		"1_2" : "metal",
		"1_3" : "jump",
		"1_5" : "falling",
		"1_6" : "metal",
		"1_7" : "metal",
		"1_8" : "metal",
		"2_1" : "metal",
		"2_2" : "metal",
		"2_6" : "metal",
		"2_8" : "metal",
		"3_1" : "falling",
		"3_2" : "metal",
		"3_3" : "metal",
		"3_6" : "jump",
		"3_8" : "metal",
		"4_3" : "metal",
		"4_4" : "metal",
		"4_8" : "metal",
		"5_1" : "jump",
		"5_4" : "corner",
		"5_5" : "metal",
		"5_6" : "metal",
		"5_7" : "falling",
		"5_8" : "falling",
		"6_1" : "metal",
		"6_3" : "metal",
		"6_6" : "exit_open",
		"6_8" : "jump",
		"7_1" : "metal",
		"7_3" : "metal",
		"7_8" : "metal",
		"8_1" : "metal",
		"8_2" : "metal",
		"8_3" : "metal",
		"8_4" : "falling",
		"8_6" : "jump",
		"8_7" : "metal",
		"8_8" : "metal"
	}

	@LevelNineteen:{
		pickups:{
			"1_1" : "true",
			"1_8" : "true",
			"8_1" : "true",
			"8_8" : "true",
		},
		startPos:{
			x:0,
			y:0
		},
		"0_0" : "corner",
		"0_1" : "falling",
		"0_7" : "metal",
		"0_8" : "metal",
		"1_0" : "falling",
		"1_1" : "metal",
		"1_2" : "metal",
		"1_3" : "metal",
		"1_4" : "metal",
		"1_5" : "metal",
		"1_6" : "jump",
		"1_7" : "jump",
		"1_8" : "metal",
		"2_1" : "metal",
		"3_1" : "metal",
		"3_3" : "jump",
		"3_4" : "falling",
		"3_5" : "metal",
		"3_7" : "falling",
		"3_8" : "metal",
		"4_1" : "metal",
		"4_3" : "falling",
		"4_4" : "exit_open",
		"4_5" : "falling",
		"4_6" : "falling",
		"4_7" : "falling",
		"5_1" : "metal",
		"5_3" : "metal",
		"5_4" : "falling",
		"5_5" : "jump",
		"5_7" : "jump",
		"5_8" : "metal",
		"6_1" : "jump",
		"6_7" : "metal",
		"6_8" : "falling",
		"7_0" : "metal",
		"7_1" : "jump",
		"7_3" : "falling",
		"7_4" : "jump",
		"7_5" : "metal",
		"7_6" : "metal",
		"7_7" : "metal",
		"7_8" : "falling",
		"8_0" : "metal",
		"8_1" : "metal",
		"8_3" : "metal",
		"8_4" : "metal",
		"8_7" : "falling",
		"8_8" : "metal"
	}

	@LevelTwenty:{
		pickups:{
			"1_0" : "true",
			"1_8" : "true",
			"3_3" : "true",
			"3_6" : "true",
			"6_3" : "true",
			"6_6" : "true",
			"9_0" : "true",
			"9_8" : "true",
		},
		startPos:{
			x:0,
			y:0
		},
		"0_0" : "corner",
		"1_0" : "falling",
		"1_1" : "falling",
		"1_2" : "falling",
		"1_3" : "falling",
		"1_4" : "falling",
		"1_5" : "falling",
		"1_6" : "falling",
		"1_7" : "falling",
		"1_8" : "falling",
		"2_0" : "falling",
		"2_1" : "falling",
		"2_8" : "falling",
		"3_0" : "falling",
		"3_1" : "falling",
		"3_3" : "falling",
		"3_4" : "falling",
		"3_5" : "falling",
		"3_6" : "falling",
		"3_8" : "falling",
		"4_0" : "falling",
		"4_1" : "falling",
		"4_3" : "falling",
		"4_6" : "falling",
		"4_8" : "falling",
		"5_0" : "falling",
		"5_1" : "falling",
		"5_3" : "falling",
		"5_6" : "falling",
		"5_8" : "falling",
		"6_0" : "falling",
		"6_1" : "falling",
		"6_3" : "falling",
		"6_4" : "falling",
		"6_5" : "falling",
		"6_6" : "falling",
		"6_7" : "falling",
		"6_8" : "falling",
		"7_0" : "falling",
		"7_1" : "falling",
		"7_5" : "falling",
		"7_6" : "falling",
		"7_7" : "falling",
		"7_8" : "falling",
		"8_0" : "falling",
		"8_1" : "falling",
		"8_2" : "falling",
		"8_3" : "falling",
		"8_4" : "falling",
		"8_5" : "falling",
		"8_6" : "falling",
		"8_7" : "falling",
		"8_8" : "falling",
		"9_0" : "falling",
		"9_1" : "falling",
		"9_2" : "falling",
		"9_3" : "falling",
		"9_4" : "falling",
		"9_5" : "falling",
		"9_6" : "falling",
		"9_7" : "falling",
		"9_8" : "falling",
		"9_9" : "exit_open"
	}

	#96x160
	@Levels = [
		Levels.LevelTwo,
		Levels.LevelOne,
		Levels.LevelThree,
		Levels.LevelFour,
		Levels.LevelFive,
		Levels.LevelSix,
		Levels.LevelSeven,
		Levels.LevelEight,
		Levels.LevelNine,
		Levels.LevelTen,
		Levels.LevelEleven,
		Levels.LevelTwelve,
		Levels.LevelThirteen,
		Levels.LevelFourteen,
		Levels.LevelFifteen,
		Levels.LevelSixteen,
		Levels.LevelSeventeen,
		Levels.LevelEighteen,
		Levels.LevelNineteen,
		Levels.LevelTwenty
	]